.TH FLL-BUILD "8" "December 2006" "" ""
.SH NAME
fll-build \- build script for a debian sid live linux cd
.SH SYNOPSIS
\fBfll-build\fR \fI[OPTIONS]\fR
.SH "DESCRIPTION"
.PP
.SH OPTIONS
.TP
\fB\-c|\-\-configfile\fR
Path to alternate configfile.
(default: /etc/fll-builder/fll-build.conf)
.TP
\fB\-h|\-\-help\fR
Information about using this program
.TP
\fB\-v|\-\-version\fR
Version and copyright information
.PP
.SH ENVIRONMENT
.PP
.SH USAGE
.PP
.RS
\fBfll-build\fR \fI--configfile /path/to/alt/configfile\fR
.RE
.PP
.SH AUTHOR
This manual page was written by Kel Modderman <kel@otaku42.de> for
the Debian GNU system (but may be used by others).
