.TH FLL-BUILD "8" "February 2007" "" ""
.SH NAME
fll-build \- build script for a debian sid `live' linux operating system
.SH SYNOPSIS
\fBfll-build\fR \fI[options]\fR
.SH DESCRIPTION
The purpose of \fIfll-builder\fR is to build a modern linux
operating system from the rich software provided by the unstable
branch of the Debian GNU/Linux project (codename: sid).
.PP
The product of fll-builder contains additional software from the 
F.U.L.L.S.T.O.R.Y project that enhances the operating system's
ability to adapt to a diverse range of hardware configurations.
.PP
Homepage: http://developer.berlios.de/projects/fullstory
.PP
.SH OPTIONS
.TP
\fB\-b|\-\-buildarea\fR
Path to temporary build area for live-cd chroot
.TP
\fB\-c|\-\-configfile\fR
Path to alternate configfile.
(default: /etc/fll-builder/fll-build.conf)
.TP
\fB\-C|\-\-copyright\fR
Copyright information
.TP
\fB\-d|\-\-debug\fR
Debug shell code execution (set -x)
.TP
\fB\-h|\-\-help\fR
Information about using this program
.TP
\fB\-k|\-\-kernel\fR
URL to kernel zip package
.TP
\fB\-n|\-\-chrootonly
Quit after preparing chroot
.TP
\fB\-o|\-\-output\fR
ISO output dir
.TP
\fB\-p|\-\-preserve\fR
Preserve build area when finished
.TP
\fB\-P|\-\-package-profile\fR
Name of packages profile. Each profile is sourced from bash lists
(arrays) located at /etc/fll-builder/packages/<NAME>.bm.
(default: kde-lite or /etc/fll-builder/packages/kde-lite.bm)
.TP
\fB\-s|\-\-source\fR
Retrieve all source packages for the release
.TP
\fB\-S|\-\-squashfs-sortfile\fR
Path to squashfs sort file
.PP
.SH USAGE
fll-build is best used with a localised configuration file. Use the default
config, /etc/fll-builder/fll-build.conf, as the template for a local config.
Comments contained in that file should be sufficient enough to describe the
purpose of each variable.
.PP
.RS
\fBfll-build\fR \fI--configfile /path/to/alt/configfile\fR
.RE
.PP
.SH AUTHOR
This manual page was written by Kel Modderman <kel@otaku42.de> for
the Debian GNU system (but may be used by others).
