#!/bin/bash
if [ $(id -u) -eq 0 ]; then
  echo Error: You must NOT be ROOT to run this script!
  exit 1
fi
source build.conf || (echo "must be run in the same dir as build.conf" && exit)
ISO=$(ls -art $BUILDSRC/*.iso | tail -n 1)
[ -e $ISO ] || (echo "No iso found in $BUILDSRC" && exit 0)
echo "Found latest iso $ISO"
MEM="256"
QEMUOPT="-monitor stdio -net nic -net user"
qemu -m $MEM -boot d -cdrom $ISO $QEMUOPT

