#!/bin/bash
source build.conf || (echo "must be run in the same dir as build.conf" && exit)
pushd $BUILDSRC
  rm -rf iso/SIDUX
  mkdir iso/SIDUX
  FILE=$(ls *.squashfs | tail -n 1)
  echo "Using $FILE"
  ln $FILE iso/SIDUX/SIDUX
  genisoimage -J -T -v -r -c "SIDUX" -no-emul-boot -boot-load-size 4 -boot-info-table -b boot/grub/iso9660_stage1_5 -c boot/grub/boot.cat -hide-rr-moved -o $FILE.iso iso
popd

