#!/bin/bash
export LANG="C"

source /root/install-packages

LOG=/root/fll-build-log
mount /proc
mount /sys
mkdir $LOG
echo "sidux-live" > /etc/debian_chroot
apt-get update > $LOG/apt-get-update
echo "Done update"
apt-get --allow-unauthenticated -y install sidux-keyrings > $LOG/apt-get-keyrings
echo "Done keyrings"
apt-get --allow-unauthenticated -y install distro-defaults > $LOG/apt-get-keyrings
echo "Done default"
source /etc/default/distro
apt-get --allow-unauthenticated -y dist-upgrade > $LOG/apt-get-dist-upgrade
echo "Done dist-upgrade"
apt-get --allow-unauthenticated -y install $BASE > $LOG/apt-get-install-base
echo "Done base"
apt-get --allow-unauthenticated -y install $DISTRO_BASE > $LOG/apt-get-install-sidux
echo "Done sidux"
apt-get --allow-unauthenticated -y install $DISTRO_XORG > $LOG/apt-get-install-siduxxorg
echo "Done siduxxorg"
apt-get --allow-unauthenticated -y install $KDE_CORE $DISTRO_KDE > $LOG/apt-get-install-kde
echo "Done kde"
adduser --gecos "$FLL_DISTRONAME User" --disabled-password $FLL_LIVE_USER
for joingroup in dialout fax voice cdrom tape sudo audio dip video plugdev users camera floppy games powerdev; do adduser "$FLL_LIVE_USER" "$joingroup"; done
passwd -l root
echo "Done users"
apt-get --allow-unauthenticated -y install $KERNELINST > $LOG/apt-get-kernelinst
pushd /root/deb/
./install-kernel.sh > $LOG/install-kernel
echo "Done kernel"
popd
#mv /etc/rc2.d /etc/rcinstall.d
#mkdir /etc/rc2.d
#ln -s /etc/init.d/xsession /etc/rc2.d/S10xsession
#for file in $(ls /etc/rc2.d | grep -v ); do
  # do we want to keep any
#done
sed -i s/id\:[0-6]\:initdefault\:/id\:5\:initdefault\:/ /etc/inittab
export KVERS
/usr/sbin/mklive-initrd > $LOG/mkinitrd
echo "Done initrd"
rm /etc/debian_chroot
umount /sys
umount /proc

