#!/bin/bash
export LANG="C"

source /root/install-packages

LOG=/root/fll-build-log
mount /proc
mount /sys
mkdir $LOG
echo "sidux-live" > /etc/debian_chroot
apt-get --allow-unauthenticated update > $LOG/apt-get-update
echo "Done update"
apt-get --allow-unauthenticated -y install sidux-keyrings sidux-keyring > $LOG/apt-get-keyrings
apt-get update
echo "Done keyrings"
apt-get -y install distro-defaults > $LOG/apt-get-defaults
echo "Done default"
source /etc/default/distro
apt-get -y dist-upgrade > $LOG/apt-get-dist-upgrade
echo "Done dist-upgrade"
apt-get -y install $BASE > $LOG/apt-get-install-base
echo "Done base"
apt-get -y install $DISTRO_BASE > $LOG/apt-get-install-distro
echo "Done sidux"
apt-get -y install $DISTRO_XORG > $LOG/apt-get-install-xorg
echo "Done siduxxorg"
apt-get -y install $KDE_CORE $DISTRO_KDE > $LOG/apt-get-install-kde
echo "Done kde"
apt-get -y install $DISTRO_ALL > $LOG/apt-get-install-all
echo "Done all"
adduser --gecos "$FLL_DISTRONAME User" --disabled-password $FLL_LIVE_USER
for joingroup in dialout fax voice cdrom tape sudo audio dip video plugdev users camera floppy games powerdev fuse; do adduser "$FLL_LIVE_USER" "$joingroup"; done
# TODO: fix sudo  and remove root password
#passwd -l root
echo "Done users"
#apt-get -y install $KERNEL > $LOG/apt-get-kernel
pushd /root/deb/
apt-get --allow-unauthenticated -y install $(ls *.deb | grep $KVERS | grep -v rt61 | perl -pi -e 's/\_.*\.
deb//')
./install-kernel.sh > $LOG/install-kernel
echo "Done kernel"
popd
#mv /etc/rc2.d /etc/rcinstall.d
#mkdir /etc/rc2.d
#ln -s /etc/init.d/xsession /etc/rc2.d/S10xsession
#for file in $(ls /etc/rc2.d | grep -v ); do
  # do we want to keep any
#done
sed -i s/id\:[0-6]\:initdefault\:/id\:5\:initdefault\:/ /etc/inittab
export KVERS
/usr/sbin/mklive-initrd > $LOG/mkinitrd
echo "Done initrd"
rm /etc/debian_chroot
umount /sys
umount /proc

