#!/bin/bash

chroot_exec apt-get update

# install gpg keyring for fll mirror
chroot_exec apt-get --allow-unauthenticated --assume-yes install "$FLL_DISTRO_NAME"-keyrings

chroot_exec apt-get update

FLL_PACKAGE_TIMESTAMP="$(date -u +%Y%m%d%H%M)"
export FLL_PACKAGE_TIMESTAMP
