#!/bin/bash

fetch_source_uris() {
	local CHROOTPKGLIST=$(mktemp -p $FLL_BUILD_CHROOT fll.pkglist.XXXX)
	local CHROOTSRCLIST=$(mktemp -p $FLL_BUILD_CHROOT fll.srclist.XXXX)
	
	# XXX: our kernel packages have no apt-gettable source, filter KVERS
	chroot_exec dpkg --get-selections | grep -v $KVERS | \
		awk '{ print $1 }' > "$CHROOTPKGLIST"
	
	chroot_exec apt-get -qq --print-uris source $(< $CHROOTPKGLIST) | \
		awk '{ gsub(/'\''/,"", $1); print $1 }' | \
		sort --unique --output="$CHROOTSRCLIST"
}

fetch_source_uris
