#!/bin/bash

# set x-www-browser, use the popular firefox/iceweasel if present
if exists_in_chroot /usr/bin/iceweasel; then
	chroot_exec update-alternatives --set x-www-browser /usr/bin/iceweasel
elif exists_in_chroot /usr/bin/konqueror; then
	chroot_exec update-alternatives --set x-www-browser /usr/bin/konqueror
fi
