#!/bin/bash

# purge unwanted packages
chroot_exec dpkg --purge cdebootstrap-helper-diverts

# remove used hacks and patches
remove_from_chroot /etc/kernel-img.conf
remove_from_chroot /usr/sbin/policy-rc.d
remove_from_chroot /etc/debian_chroot
remove_from_chroot /etc/hosts
remove_from_chroot /etc/resolv.conf
remove_from_chroot /etc/apt/apt.conf

# remove live-cd mode identifier
rmdir -v "${FLL_BUILD_CHROOT}${FLL_MOUNTPOINT}"
