#!/bin/bash

# a few dæmons are broken if log files are missing, 
# therefore nuke log and spool files while preserving permissions
find	"${FLL_BUILD_CHROOT}/var/cache/" \
	"${FLL_BUILD_CHROOT}/var/log/" \
		   -name \*\\.gz \
		-o -name \*\\.bz2 \
		-o -name \*\\.[0-9][0-9]? \
			-exec rm -f {} \;

find	"${FLL_BUILD_CHROOT}/var/log/" \
	"${FLL_BUILD_CHROOT}/var/mail/" \
	"${FLL_BUILD_CHROOT}/var/spool/" \
		-type f \
		-size +0 \
			-exec cp /dev/null '{}' \;
